name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  check:
    uses: ./.github/workflows/check.yml

  publish:
    needs: check
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - run: uv build --locked
      - uses: pypa/gh-action-pypi-publish@release/v1
